Add publish methods overloads with offset and count
nats-io/stan.net pull request #195
Opened 2020-12-02 20:05 UTC by Semax

Hi,

This is an attempt to improve publishing methods to provide more options for serialization and array recycling usage (#194). 
I hope it'll be useful to other stan.net users.

Thanks.

2020-12-02 20:12 UTC, watfordgnf reviewed
Some minor nits/suggestions.

2020-12-02 20:12 UTC, watfordgnf commented on src/STAN.Client/ProtocolSerializer.cs
>              if (data != null)
```suggestion
            if (data != null && count > 0)
```

2020-12-02 20:12 UTC, watfordgnf commented on src/STAN.Client/StanConnection.cs
> +            return publish(subject, data, offset, length, handler).GUID;
```suggestion
        public string Publish(string subject, byte[] data, int offset, int count, EventHandler<StanAckHandlerArgs> handler)
        {
            return publish(subject, data, offset, count, handler).GUID;
```

2020-12-02 20:35 UTC, Semax commented
@watfordgnf, 
Thanks for your helpful suggestions.

2020-12-02 20:42 UTC, watfordgnf approved these changes
Pending @ColinSullivan1 and CI.

2020-12-05 18:56 UTC, ColinSullivan1 requested changes
This is great - thanks for the PR!

One small ask - In testing could you also sub and receive the message and check that the expected payload was received?  E.g. a new testPubSubOffset() test, similar to [testBasicPubSub()](https://github.com/nats-io/stan.net/blob/b5c310d307e1e0c78f7dd026b26bb7541785ca0a/src/Tests/IntegrationTests/BasicTests.cs#L211) except it'd only need to publish check the received payload.

2020-12-05 20:38 UTC, Semax commented
@ColinSullivan1,
I've added the requested test.

2020-12-05 20:48 UTC, ColinSullivan1 approved these changes
LGTM.  Thanks!

2020-12-05 20:48 UTC, merged